### PR TITLE
generic: Fix help text

### PR DESCRIPTION
**Pull request by raffenet**

### CODE REVIEW

**Review by artpol84 — APPROVED** [review]
Thanks, @raffenet!

Are you planning to use it? Looking forward for more contributions!

**Comment by raffenet** [comment]
> Thanks, @raffenet!
> 
> Are you planning to use it? Looking forward for more contributions!

I used it for my UCX workshop talk last year. I'm re-running some of the same experiments for a different talk later this month.

image

**Comment by artpol84** [comment]
Pretty cool scaling but the absolute value is on the low side!
4M/sec isn't what I'd expect to see for a single thread. 
Is this an MPI-level or a UCX level measurement?

**Comment by raffenet** [comment]
> Pretty cool scaling but the absolute value is on the low side! 4M/sec isn't what I'd expect to see for a single thread. Is this an MPI-level or a UCX level measurement?

It's from MPI. What value would you expect? I might not have built UCX in the most optimized manner.

**Pull request merged**
